### ISSUE TITLE
[XF] NavigationService breaks on GoBack (Xamarin version 1.4.4.6392)

### ISSUE THREAD

**Issue by ValdimarThor** [PrismLibrary/Prism#104]
Navigate.GoBack works fine on earlier version but breaks with "Sequence contains no elements" on current XF version (1.4.4.6392)

Here's the stacktrace
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Xamarin.Forms.Platform.WinPhone.Platform.PopModalAsync(Boolean animated)
   at Xamarin.Forms.NavigationProxy.OnPopModal(Boolean animated)
   at Xamarin.Forms.Application.NavigationImpl.<OnPopModal>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Prism.Navigation.PageNavigationService.<DoPop>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)

**Comment by brianlagunas** [comment]
Thanks for submitting this.  I haven't tried 1.4.4 yet, so I'll have to look into this.  I find this interesting though since all the navigation service is doing is calling the Pop methods supplied by Xamarin.

**Comment by ValdimarThor** [comment]
Yeah I couldnt believe it myselft, had to make new solution from the default templates, make it work with PRISM, then update the XF nuget packages to see it fail. Very strange indeed

**Comment by brianlagunas** [comment]
I upgraded the projects to the latest version of XF 1.4.4.6392, and then ran the sample, and I got the same error.  This is very strange.  I think this is an XF issue, because absolutely nothing else changed expect upgrading XF.

**Comment by brianlagunas** [comment]
Just reached out to Xamarin.  Seems this is a bug being reported by others as well.  I am going to wait to upgrade Prism until this has been addressed by Xamarin.

**Comment by ValdimarThor** [comment]
Good to know, hope Xamarin fixes this bug soon :)

**Comment by brianlagunas** [comment]
This has been fixed
