### ISSUE TITLE
DirectoryModuleCatalog throws exception when resolving certain assembly dependencies

### ISSUE THREAD

**Issue by gtaylor1981** [PrismLibrary/Prism#1329]
﻿### Description

While resolving assemblies, using [`DirectoryModuleCatalog.Desktop`](https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.Desktop.cs) the local binding policy is not applied to reflection-only assembly loads.
This has caused problems while using assemblies defined by .NET Standard (in netstandard.dll) which have dependencies such as "`System, Version=0.0.0.0, publicKey=....`" then use `app.config` to define
binding redirects.

### Steps to Reproduce

Bootstrap a project using `DirectoryModuleCatalog` from a folder containing .NET Standard DLLs with such versionless dependencies.

### Expected Behavior

That the assemblies and dependencies are loaded according to their defined binding redirections, or that assemblies which cannot be loaded are ignored.

### Actual Behavior

An unhandled exception is thrown and the program exits:
```
Could not load file or assembly 'System, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Practices.Prism.Modularity.DirectoryModuleCatalog.InnerModuleInfoLoader.<>c__DisplayClassf.<GetNotAllreadyLoadedModuleInfos>b__b(FileInfo file) in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Modularity\DirectoryModuleCatalog.Desktop.cs:line 165
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Practices.Prism.Modularity.DirectoryModuleCatalog.InnerModuleInfoLoader.GetModuleInfos(String path) in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Modularity\DirectoryModuleCatalog.Desktop.cs:line 133
   at Microsoft.Practices.Prism.Modularity.DirectoryModuleCatalog.InnerModuleInfoLoader.GetModuleInfos(String path)
   at Microsoft.Practices.Prism.Modularity.DirectoryModuleCatalog.InnerLoad() in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Modularity\DirectoryModuleCatalog.Desktop.cs:line 81
   at Microsoft.Practices.Prism.Modularity.ModuleCatalog.Initialize() in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Modularity\ModuleCatalog.cs:line 344
   at Microsoft.Practices.Prism.Modularity.ModuleManager.Run() in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Modularity\ModuleManager.cs:line 110
   at Microsoft.Practices.Prism.UnityExtensions.UnityBootstrapper.InitializeModules() in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism.UnityExtensions\UnityBootstrapper.cs:line 192
   at Microsoft.Practices.Prism.UnityExtensions.UnityBootstrapper.Run(Boolean runWithDefaultConfiguration) in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism.UnityExtensions\UnityBootstrapper.cs:line 115
   at Microsoft.Practices.Prism.Bootstrapper.Run() in c:\prj\PrismNew\Prism4\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Bootstrapper.cs:line 77
   at MyApplication.PrismUnityBootstrapper.Run()
   at MyApplication.Program.Main(String[] args)
```

### Basic Information

- Version with issue: All (v4.1 - v7.0)

### Solution

I could find no workaround for this problem, other than to import the `DirectoryModuleCatalog` and rewrite parts of it.

I had a few ideas for a solution (in increasing order of complexity):

1. **Apply the binding policy before loading assemblies.**

   Done by changing the `args.Name` parameter here: `Assembly.ReflectionOnlyLoad(args.Name);`
   to: `AppDomain.CurrentDomain.ApplyPolicy(args.Name)`

   However, adding [ApplyPolicy](https://docs.microsoft.com/en-gb/dotnet/api/system.appdomain.applypolicy) could result in different behavior, so perhaps this could just be attempted as a fallback if loading the dependency throws an exception, or enabled via a new flag.

2. **Catch and handle the exception, ignoring assemblies whose dependencies cause the problem, then continue processing other assemblies.** 

   This is already done while loading assemblies (in `GetNotAlreadyLoadedModuleInfos`) but not while resolving their dependencies (in `OnReflectionOnlyResolve`).

3. **Do nothing, but allow DirectoryModuleCatalog to be extended**

   Unfortunately the `DirectoryModuleCatalog` class is relatively difficult to extend (possibly because of the constraints of working with `AppDomains` and the need to marshal everything to the private inner class).
    Ideally, assembly 'discovery' and assembly 'inspection' would be done in separate virtual methods, allowing the overload the 'discovery' method to provide a list of 'safe' assemblies (which would then be inspected for module attributes).

4. **Add option to ignore certain DLLs during bootstrapping.**

   It could work via a filter callback, or regular expression (i.e. ignore System.* or Microsoft.*).
   This feature might also be useful anyway to reduce unnecessary work at startup (I have 230+ assemblies and only ~10 have modules in).

### Related Issue
https://github.com/PrismLibrary/Prism/issues/110

**Comment by brianlagunas** [comment]
Hmmmm.... I'm not convinced this is something that Prism should be responsible for.  Prism assumes that the developer has made sure all dependencies are in place when dynamically loading modules.  Also, it seems you do have a work-around by creating your own directory module catalog and implementing the feature specific to your scenario.

I am open to making the DirectoryModuleCatalog more extensible (option 3). If you would like to submit a PR for review with your proposed changes, I would be willing to review it for consideration.

**Comment by gtaylor1981** [comment]
Submitted https://github.com/PrismLibrary/Prism/pull/1334

**Comment by brianlagunas** [comment]
See my response in the PR for why this issue is being closed.
