### ISSUE TITLE
DryIoc.dll Issue when updating to version 3.0.1

### ISSUE THREAD

**Issue by kevinvella** [PrismLibrary/Prism#1496]
Hi,

I've updated to version 3.0.1 from version 2.12.6 and it gives me the following, on both Android and iOS ( using .Net standard )

System.MissingMethodException void DryIoc.Registrator.Register<!0,!1>(DryIoc.IRegistrator,DryIoc.IReuse,DryIoc.Made,DryIoc.Setup,DryIoc.IfAlreadyRegistered,object)

Working with 
Prism Prism.Core - 7.0.0.396 
Prism.DryIoc.Forms - 7.0.0.396 
Prism.Forms - 7.0.0.396
Xamarin Forms - 3.1.0.583944

Downgrading to v2.12.6 works

Please advise if I'm missing something
Thanks in advance 
Kevin

**Comment by torturegenitale** [comment]
Same error here. I have managed to have more details:

> Severity    Code    Description Project File    Line    Suppression State
Error       The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Prism.DryIoc.PrismApplication::RegisterRequiredTypes(Prism.Ioc.IContainerRegistry)' in assembly: 'Prism.DryIoc.Forms.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void DryIoc.Registrator::Register(DryIoc.IRegistrator,DryIoc.IReuse,DryIoc.Made,DryIoc.Setup,DryIoc.IfAlreadyRegistered,System.Object)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() AllyNations.Android C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets    1812

**Comment by kevinvella** [comment]
Cheers. From VS fro mac i wasn't able to view the stack trace. Only seeing the exception

![screen shot 2018-07-11 at 12 53 03](https://user-images.githubusercontent.com/15779395/42571488-9ef731ca-8517-11e8-9df6-4e47a1503dcb.png)

**Comment by dansiegel** [comment]
This issue is caused by your changing major versions. For now you'll need to roll back to 2.X, we'll be updating to DryIoc 3 soon
