### ISSUE TITLE
UWP Failed to assign to property 'Prism.Windows.Mvvm.ViewModelLocator.AutoWireViewModel'

### ISSUE THREAD

**Issue by mjmeans** [PrismLibrary/Prism#1565]
I am having inconsistent behavior. This occurs "sometimes". Each time I build the project it has perhaps a 1 in 20 chance of having this problem. It doesn't seem to matter if it is an incremental build or a clean/build or rebuild. Here are the error messages reported in VS 2017 IDE Exception Helper and in the Output window:

```
Failed to assign to property 'Prism.Windows.Mvvm.ViewModelLocator.AutoWireViewModel'. [Line: 11 Position: 5]
  Source=Windows
  StackTrace:
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at MyApp2.UWP.Views.ArtistDetailPage.InitializeComponent() in C:\Users\Mark\Documents\Visual Studio 2017\Projects\MyApp\MyApp2.UWP\obj\x86\Debug\Views\ArtistDetailPage.g.i.cs:line 43
   at MyApp2.UWP.Views.ArtistDetailPage..ctor() in C:\Users\Mark\Documents\Visual Studio 2017\Projects\MyApp\MyApp2.UWP\Views\ArtistDetailPage.xaml.cs:line 18
   at MyApp2.UWP.MyApp2_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_42_ArtistDetailPage() in C:\Users\Mark\Documents\Visual Studio 2017\Projects\MyApp\MyApp2.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 411
   at MyApp2.UWP.MyApp2_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\Mark\Documents\Visual Studio 2017\Projects\MyApp\MyApp2.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 1825


Exception thrown: 'Microsoft.Practices.Unity.ResolutionFailedException' in Prism.Windows.dll
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in MyApp2.UWP.exe
WinRT information: Failed to assign to property 'Prism.Windows.Mvvm.ViewModelLocator.AutoWireViewModel'. [Line: 11 Position: 5]
An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in MyApp2.UWP.exe but was not handled in user code
WinRT information: Failed to assign to property 'Prism.Windows.Mvvm.ViewModelLocator.AutoWireViewModel'. [Line: 11 Position: 5]
The text associated with this error code could not be found.
```

I'm using a Windows Template Studio based project. In all cases when this occurs, the page being navigated to is called using `ctor (INavigationService navigationServiceInstance, IEventAggregator eventAggregator)`. When this occurs, pages that do not reference **IEventAggregator** still navigate correctly. **ConfigureContainer** looks like this:

```
      protected override void ConfigureContainer()
        {
            // register a singleton using Container.RegisterType<IInterface, Type>(new ContainerControlledLifetimeManager());
            base.ConfigureContainer();
            Container.RegisterType<IDevCenterNotificationsService, DevCenterNotificationsService>(new ContainerControlledLifetimeManager());
            Container.RegisterType<IBackgroundTaskService, BackgroundTaskService>(new ContainerControlledLifetimeManager());
            Container.RegisterInstance<IResourceLoader>(new ResourceLoaderAdapter(new ResourceLoader()));
            Container.RegisterInstance<IEventAggregator>(new EventAggregator());
        }
```

**Comment by brianlagunas** [comment]
The old version of Prism for UWP is no longer supported. We are in the process of rewriting our UWP guidance. You can start playing with the CI builds if you like, but it will be a completely different way of building UWP apps, and should be considered a major breaking change. I'm closing this for a number of reasons. First, we aren't putting any time in trying to reproduce something that happens once every 20 times when a reproduction app hasn't been provided.  Second, We are no longer working on the current version of UWP and are putting all our efforts into the rewrite.

**Comment by mjmeans** [comment]
I'm using Windows Template Studio so CI builds are a non-starter.
