### ISSUE TITLE
Prism Problem&Solution get Exception (Mastering the TabControl) Exception

### ISSUE THREAD

**Issue by SML913** [PrismLibrary/Prism#1569]
### Description

I followed the Prism Problem and Solution courses of @brianlagunas. I first implemented the example of Loading  Dependent View then in the same project I Implemented the Example of Mastering TabControl. in order to make a tabControl application with RibbonTabs. But I am getting the following Exception:

Prism.Regions.UpdateRegionsException
  HResult=0x80131500
  Message=An exception occurred while trying to create region objects. 
    - The most likely causing exception was: 'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Prism.Regions.Behaviors.RegionCreationException: An exception occurred while creating a region with name 'ChildRegion'. The exception was: System.ArgumentException: Region with the given name is already registered: ChildRegion
   at Prism.Regions.RegionManager.RegionCollection.Add(IRegion region)
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.TryRegisterRegion()
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.StartMonitoringRegionManager()
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.OnAttach()
   at Prism.Regions.RegionBehavior.Attach()
   at Prism.Regions.RegionBehaviorCollection.Add(String key, IRegionBehavior regionBehavior)
   at Prism.Regions.RegionAdapterBase`1.AttachDefaultBehaviors(IRegion region, T regionTarget)
   at Prism.Regions.RegionAdapterBase`1.Initialize(T regionTarget, String regionName)
   at Prism.Regions.RegionAdapterBase`1.Prism.Regions.IRegionAdapter.Initialize(Object regionTarget, String regionName)
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName).  ---> System.ArgumentException: Region with the given name is already registered: ChildRegion
   at Prism.Regions.RegionManager.RegionCollection.Add(IRegion region)
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.TryRegisterRegion()
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.StartMonitoringRegionManager()
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.OnAttach()
   at Prism.Regions.RegionBehavior.Attach()
   at Prism.Regions.RegionBehaviorCollection.Add(String key, IRegionBehavior regionBehavior)
   at Prism.Regions.RegionAdapterBase`1.AttachDefaultBehaviors(IRegion region, T regionTarget)
   at Prism.Regions.RegionAdapterBase`1.Initialize(T regionTarget, String regionName)
   at Prism.Regions.RegionAdapterBase`1.Prism.Regions.IRegionAdapter.Initialize(Object regionTarget, String regionName)
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName)
   --- End of inner exception stack trace ---
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName)
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.TryCreateRegion()
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.OnUpdatingRegions(Object sender, EventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Prism.Events.WeakDelegatesManager.Raise(Object[] args)
   at Prism.Regions.RegionManager.UpdateRegions()'.
    But also check the InnerExceptions for more detail or call .GetRootException(). 
  Source=Prism.Wpf
  StackTrace:
   at Prism.Regions.RegionManager.UpdateRegions()
   at Prism.Regions.RegionManager.RegionCollection.get_Item(String regionName)
   at WpfApp6.Prism.DependentViewRegionBehavior.<Views_CollectionChanged>b__3_1(DependentViewInfo x) in E:\App\WpfApp6\Prism\DependentViewRegionBehavior.cs:line 57
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at WpfApp6.Prism.DependentViewRegionBehavior.Views_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in E:\App\WpfApp6\Prism\DependentViewRegionBehavior.cs:line 57
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at Prism.Regions.ViewsCollection.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Prism.Regions.ViewsCollection.NotifyRemove(IList items, Int32 originalIndex)
   at Prism.Regions.ViewsCollection.RemoveFromFilteredList(Object item)
   at Prism.Regions.ViewsCollection.OnItemMetadataChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Prism.Regions.ItemMetadata.InvokeMetadataChanged()
   at Prism.Regions.ItemMetadata.DependencyPropertyChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Prism.Regions.Region.Deactivate(Object view)
   at Prism.Regions.Behaviors.SelectorItemsSourceSyncBehavior.ActiveViews_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at Prism.Regions.ViewsCollection.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Prism.Regions.ViewsCollection.NotifyAdd(IList items, Int32 newStartingIndex)
   at Prism.Regions.ViewsCollection.NotifyAdd(Object item)
   at Prism.Regions.ViewsCollection.OnItemMetadataChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Prism.Regions.ItemMetadata.InvokeMetadataChanged()
   at Prism.Regions.ItemMetadata.DependencyPropertyChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Prism.Regions.Region.Activate(Object view)
   at Prism.Regions.RegionNavigationService.ExecuteNavigation(NavigationContext navigationContext, Object[] activeViews, Action`1 navigationCallback)

Inner Exception 1:
RegionCreationException: An exception occurred while creating a region with name 'ChildRegion'. The exception was: System.ArgumentException: Region with the given name is already registered: ChildRegion
   at Prism.Regions.RegionManager.RegionCollection.Add(IRegion region)
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.TryRegisterRegion()
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.StartMonitoringRegionManager()
   at Prism.Regions.Behaviors.RegionManagerRegistrationBehavior.OnAttach()
   at Prism.Regions.RegionBehavior.Attach()
   at Prism.Regions.RegionBehaviorCollection.Add(String key, IRegionBehavior regionBehavior)
   at Prism.Regions.RegionAdapterBase`1.AttachDefaultBehaviors(IRegion region, T regionTarget)
   at Prism.Regions.RegionAdapterBase`1.Initialize(T regionTarget, String regionName)
   at Prism.Regions.RegionAdapterBase`1.Prism.Regions.IRegionAdapter.Initialize(Object regionTarget, String regionName)
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName). 

Inner Exception 2:
ArgumentException: Region with the given name is already registered: ChildRegion

### Expected Behavior
by using the scoped region with Behavior  I should be able to have child navigation in the TabControl and show dependent views in the RibbonTab.
### Actual Behavior
Get an Exception
### Basic Information

- Version with issue: Prism.Wpf 6.3.0
- Last known good version:
-
- IDE:
Visual Studio 2017 v15.8.5

### Reproduction Link
here is the reproduction link.
https://drive.google.com/open?id=1T7GjzPyfzS_Xwx1zbqKI7so6BBRfzDWB

**Comment by brianlagunas** [comment]
I'm sorry, but we do not provide support for Pluralsight courses here. The error tells me you are running into a scoped region problem. So you have something wrong. I would suggest downloading the samples that come with the course and study them or modify them to meet your needs. The good news is at least you know where to start looking... scoped regions.
