### ISSUE TITLE
ContainsRegionInfo throws nullreference exception in UpdateRegions API

### ISSUE THREAD

**Issue by rithuikr7** [PrismLibrary/Prism#1642]
### Description

During the activation of my view I check the existence of a region in region collection in region manager using ContainsRegionInfo API. However this threw a null reference exception in UpdateRegions.

### Steps to Reproduce

1. Try to activate my view in a predefined region.

### Expected Behavior
View should be activated
### Actual Behavior
Application crashed in the UI.
### Basic Information

- Version with issue:PRISM 6.1

Call stack:
Call stack:
Runtime Terminating: True
App.FailOnThreadException: True 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Prism.Events.WeakDelegatesManager.<>c.<Raise>b__3_1(DelegateReference listener)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Prism.Events.WeakDelegatesManager.Raise(Object[] args)
   at Prism.Regions.RegionManager.UpdateRegions()
   at Prism.Regions.RegionManager.RegionCollection.ContainsRegionWithName(String regionName)

**Comment by brianlagunas** [comment]
Required reproduction application not provided.
