### ISSUE TITLE
Making a new prism wpf app throws error Could Not Load File or Assembly Unity.Container 5.11.1.0

### ISSUE THREAD

**Issue by CodyWHageman** [PrismLibrary/Prism#1854]
### Description

I am trying to make myself a new app for different dev tools I would be using. I did exactly what I said in the Steps to reproduce and I'm getting the error explained below. I have not manually updated anything just installed and thats it. I'm basically getting a conflict of packages and don't understand why.

### Steps to Reproduce

1. Create new WPF App (.NetFramework 4.6.1)
2. Install Nuget Package Prism.Wpf
3. Install Nuget Package Prism.Unity
4. Change App.Xaml/App.Xaml.cs to inherit PrismApplication
5. Run app

### Expected Behavior
Should open MainWindow

### Actual Behavior
Breaks with the error -->
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Unity.Container, Version=5.11.1.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Prism.Unity.Wpf
StackTrace:
   at Prism.Unity.Ioc.UnityContainerExtension..ctor()
   at Prism.Unity.PrismApplication.CreateContainerExtension()
   at Prism.PrismApplicationBase.Initialize()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WardKraft.DevShop.App.Main() in C:\Users\chageman\Projects\WardKraft.DevShop\WardKraft.DevShop\obj\Debug\App.g.cs:line 57

Inner Exception 1:
FileLoadException: Could not load file or assembly 'Unity.Container, Version=5.8.11.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Basic Information

- Version with issue:  v7.1.0.431
- IDE: VS 2017

### Reproduction Link
[Example](https://github.com/CodyWHageman/TestPrismSevenWpfApp)

**Comment by brianlagunas** [comment]
Works for me!
