### ISSUE TITLE
[Bug] Navigation Service Not Thread Safe For Tasks

### ISSUE THREAD

**Issue by Axemasta** [PrismLibrary/Prism#1880]
### Description
The navigation service appears to be crashing when called from a `Task`.

My scenario is the following:

- My app loads splash
- The first page I load looks like the splash, but it plays an animation and does some background tasks (inits/checks the data layer & talks to an api).
- When loading is completed the app loads the main menu

The first page loads but the second page can't be loaded and the navigation service has an error about threading. 

If the method calling the code is not a `Task` then navigation is successful.
If the method is a `Task` and the `NavigationService` call is wrapped in `Device.BeginInvokeOnMainThread` then navigation will be successful.

Example Code:
```
public LoadingPageViewModel(INavigationService navigationService) : base(navigationService)
{
    _navigationService = navigationService;

    Task.Run(LoadApp);
}

private async Task LoadApp()
{
    Debug.WriteLine("Loading the app");

    await Task.Delay(2000);

    Debug.WriteLine("App loaded, navigating to main menu");

    var nav = await _navigationService.NavigateAsync(nameof(Views.MenuPage));

    if (!nav.Success)
    {
        Debug.WriteLine($"Navigation unsuccessful, reason: {nav.Exception.Message}");
    }
}
```

### Steps to Reproduce

1. Load a page in the App class
2. This class should call a task in it's ctor that does something and then loads another page

### Expected Behavior
The actions are performed and the next page is loaded

### Actual Behavior
The navigation service records an exception and doesn't navigate. The exception is from the platform navigation service (ie UIKit for iOS) talking about thread safety.

### Basic Information

- Version with issue: Prism.DryIoc.Forms 7.2.0.1367
- Last known good version:
- Xamarin.Forms version: 4.1.0.673156
- IDE: VSMac 2017,2019. VSCommunity (win) 2019.

### Exception - iOS

`Message`: `UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.`

`Stack Trace`:
```
  at UIKit.UIApplication.EnsureUIThread () [0x00020] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIApplication.cs:89 
  at UIKit.UIViewController.get_View () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIViewController.g.cs:2978 
  at Xamarin.Forms.Platform.iOS.Platform.EndEditing () [0x00051] in <612eab01c6f546df983c0637f996b4cd>:0 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PushModalAsync (Xamarin.Forms.Page modal, System.Boolean animated) [0x00000] in <612eab01c6f546df983c0637f996b4cd>:0 
  at Xamarin.Forms.Internals.NavigationProxy.OnPushModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x00022] in D:\a\1\s\Xamarin.Forms.Core\NavigationProxy.cs:212 
  at Xamarin.Forms.Application+NavigationImpl.<>n__1 (Xamarin.Forms.Page modal, System.Boolean animated) <0x10336bfc0 + 0x0004b> in <4542de7f0f544d51b46d63bd15d5f6b5#e35d0a438c4de7c95cd807dfbd8543c8>:0 
  at Xamarin.Forms.Application+NavigationImpl+<OnPushModal>d__3.MoveNext () [0x00065] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:395 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<>c__DisplayClass41_1+<<ProcessNavigationForContentPage>b__0>d.MoveNext () [0x00050] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:492 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<DoNavigateAction>d__48.MoveNext () [0x00137] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:702 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<ProcessNavigationForContentPage>d__41.MoveNext () [0x001a3] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:490 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<ProcessNavigation>d__33.MoveNext () [0x001ca] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:365 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<NavigateInternal>d__32.MoveNext () [0x000f9] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:322 
```

### Exception - Android
`Message`: `Only the original thread that created a view hierarchy can touch its views.`
`Stack Trace`:
```
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <fdf05f528e174febb3e55b587dbab368>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <fdf05f528e174febb3e55b587dbab368>:0 
  at Android.Views.ViewGroup.AddView (Android.Views.View child) [0x00031] in <d9e99b55e96444569d54148253f9c212>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.Platform.PresentModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:385 
  at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.INavigation.PushModalAsync (Xamarin.Forms.Page modal, System.Boolean animated) [0x00055] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:165 
  at Xamarin.Forms.Application+NavigationImpl.OnPushModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x0007d] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:395 
  at Prism.Navigation.PageNavigationService+<>c__DisplayClass41_1.<ProcessNavigationForContentPage>b__0 () [0x00050] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:492 
  at Prism.Navigation.PageNavigationService.DoNavigateAction (Xamarin.Forms.Page fromPage, System.String toSegment, Xamarin.Forms.Page toPage, Prism.Navigation.INavigationParameters parameters, System.Func`1[TResult] navigationAction, System.Action onNavigationActionCompleted) [0x00137] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:702 
  at Prism.Navigation.PageNavigationService.ProcessNavigationForContentPage (Xamarin.Forms.Page currentPage, System.String nextSegment, System.Collections.Generic.Queue`1[T] segments, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x001a3] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:490 
  at Prism.Navigation.PageNavigationService.ProcessNavigation (Xamarin.Forms.Page currentPage, System.Collections.Generic.Queue`1[T] segments, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x001ca] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:365 
  at Prism.Navigation.PageNavigationService.NavigateInternal (System.Uri uri, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x000f9] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:322 
  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7753)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1225)
	at android.view.View.requestLayout(View.java:23093)
	at android.view.View.requestLayout(View.java:23093)
	at android.view.View.requestLayout(View.java:23093)
	at android.view.View.requestLayout(View.java:23093)
	at android.view.View.requestLayout(View.java:23093)
	at android.view.View.requestLayout(View.java:23093)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
	at android.view.View.requestLayout(View.java:23093)
	at android.view.ViewGroup.addView(ViewGroup.java:4863)
	at android.view.ViewGroup.addView(ViewGroup.java:4805)
	at android.view.ViewGroup.addView(ViewGroup.java:4778)
```

### Reproduction Link
[Prism Nav Issue.zip](https://github.com/PrismLibrary/Prism/files/3512501/Prism.Nav.Issue.zip)

**Comment by brianlagunas** [comment]
This is to be expected. The nav service is created on a UI thread, and when dealing with multiple threads, you can only use an object on the same thread it was created.

**Comment by brianlagunas** [comment]
Also, you can't navigate from a ctor. The page isn't even part of the nav stack yet.

**Comment by Axemasta** [comment]
Is the navigation service using `Device.BeginInvokeOnMainThread` under the hood? the whole process works fine for me when I wrap my nav service call in this.

I guess i'll have to move my code around but it's essentially a copy of a native iOS app I had where I had a spoof loading page that was exactly the same as the splash but it did a load of loading tasks and then presented the main app after loading.

**Comment by brianlagunas** [comment]
No, you would have to wrap your code in this when required. Prism calls the XF navigation APIs just liek you would in a non-Prism app. This keeps the behavior the exact same and expectations clear.
