### ISSUE TITLE
[Bug] System.InvalidCastException on ComboBox

### ISSUE THREAD

**Issue by jxnass** [PrismLibrary/Prism#1891]
### Description
When an opened ComboBox Selection is getting closed an Exception will be thrown. The Exception is getting handled, and the closing works however there shouldnt be an Exception.

### Steps to Reproduce

1. Create an empty WPF Visual Studio Project
2. Add the `Prism.Wpf` Nuget Package in the project
3. Create an Window containing an `ComboBox` and a Binding to `ItemsSource`
4. Create an Model Class for Window and a Binding Property
5. Add some Items to the ComboBox
6. Start Project and click the ComboBox
7. Dismiss the ComboBox Selection
8. In the Output Panel you should see an Exception getting throwed

### Expected Behavior
There shouldnt be an InvalidCastException getting throwed. 

### Actual Behavior
The Action works as expected, the items in the combobox is complete, however in the visual studio output panel there is an Exception getting throwed:
`
Ausnahme ausgelöst: "System.InvalidCastException" in PresentationFramework.dll
Unable to cast object of type 'System.Collections.Hashtable' to type 'System.String'.
   at System.Windows.Markup.XmlAttributeProperties.GetXmlNamespaceMaps(DependencyObject dependencyObject)
Ausnahme ausgelöst: "System.Reflection.TargetInvocationException" in mscorlib.dll
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
Ausnahme ausgelöst: "System.FormatException" in PresentationCore.dll
Token is not valid.
   at MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context)
Ausnahme ausgelöst: "System.FormatException" in PresentationCore.dll
Token is not valid.
   at MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context)
Ausnahme ausgelöst: "System.FormatException" in PresentationCore.dll
Token is not valid.
   at MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context)
Ausnahme ausgelöst: "System.FormatException" in PresentationCore.dll
Token is not valid.
   at MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context)
Das Programm "[20296] PropertyBug.exe" wurde mit Code 0 (0x0) beendet.
`

### Basic Information

- Prism.Wpf Version with issue: 7.2.0.1367
- IDE: Visual Studio Professional 2019 16.2.3 (.NET Framework 4.7.03190, project Version 4.5)

### Reproduction Link

I created an Sample Application Repository on GitHub [Sample Bug Reproduction](https://github.com/jxnass/prism-bug-sample)

**Comment by brianlagunas** [comment]
This has nothing to do with Prism
