### ISSUE TITLE
[Bug] PrismApplicationBase and PrismBootstrapperBase - NullReference Exception

### ISSUE THREAD

**Issue by devriesb13** [PrismLibrary/Prism#2106]
### Description

I'm getting a NullReference Exception when these base classes are trying to ConfigureViewModelLocator on startup.

### Steps to Reproduce

1. Open Prism Sample 08-ViewModelLocator
2. Upgraded to current 8.0.0.1717-ci
3. Set project to .net core 3.1
4. Started debug
5. Crash

### Expected Behavior
The window should load and and bind to the viewmodel

### Actual Behavior
NullReference exception

Stack trace
   at Prism.PrismInitializationExtensions.<>c__DisplayClass0_0.<ConfigureViewModelLocator>b__0(Object view, Type type)
   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(Object view, Action`2 setDataContextCallback)
   at Prism.Mvvm.ViewModelLocator.AutoWireViewModelChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   at System.Xaml.XamlObjectWriter.SetValue(Object inst, XamlMember property, Object value)
   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent)
   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ViewModelLocator.Views.MainWindow.InitializeComponent() in C:\Ben\Source Control\Miscellaneous\Prism-Samples-Wpf\08-ViewModelLocator\ViewModelLocator\Views\MainWindow.xaml:line 1

### Basic Information

- Version with issue: 8.0.0.1717-ci
- Last known good version: -
- IDE: VS2019

### Screenshots

![image](https://user-images.githubusercontent.com/10214916/80553890-c2c3ab80-8a0e-11ea-83ce-3b0b77fee5c3.png)

### Reproduction Link

https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/08-ViewModelLocator

**Comment by brianlagunas** [comment]
Good catch! Thanks for testing the CI build for us.

**Comment by brianlagunas** [comment]
Fixed with #2107
