### ISSUE TITLE
[Bug] Prism Forms for WPF not working on 7.2.0.1422 version

### ISSUE THREAD

**Issue by raV720** [PrismLibrary/Prism#2123]
After update Prism Forms library from 7.0.0.396 to 7.2.0.1422 I have error on WPF platform:

System.TypeLoadException: 'Method 'add_ModuleDownloadProgressChanged' in type 'Prism.Modularity.ModuleManager' from assembly 'Prism.Forms, Version=7.2.0.1422, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

Stack trace:
```
   at Prism.PrismApplicationBase.RegisterRequiredTypes(IContainerRegistry containerRegistry)
   at Prism.DryIoc.PrismApplication.RegisterRequiredTypes(IContainerRegistry containerRegistry)
   at Prism.PrismApplicationBase.Initialize()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase..ctor(IPlatformInitializer platformInitializer, Boolean setFormsDependencyResolver)
   at Prism.DryIoc.PrismApplication..ctor()
   at PrismWpfBug.App..ctor() in C:\PrismWpfBug\PrismWpfBug\PrismWpfBug\App.cs:line 11
   at PrismWpfBug.WPF.MainWindow..ctor() in C:\PrismWpfBug\PrismWpfBug\PrismWpfBug.WPF\MainWindow.xaml.cs:line 27
```

Reproduction sample:
https://bitbucket.org/equo/prismwpfbug/src/master/

**Comment by brianlagunas** [comment]
Prism for XF does not support WPF. If you would like a WPF project, we recommend creating an actual WPF application.
