### ISSUE TITLE
[Bug] RegisterManySingleton method is not registering interfaces to the container

### ISSUE THREAD

**Issue by yurislav** [PrismLibrary/Prism#2245]
### Description

After update `prism.unity` from `8.0.0.1850-pre` to `8.0.0.1909`, the `IContainerRegistryExtensions.RegisterManySingleton` extension method does not work as expected - container could not resolve registered interfaces

### Steps to Reproduce

1. Setup an prism.wpf app with unity container
2. Register the class to the container as singleton, associated with two interfaces (e.g. `containerRegistry.RegisterManySingleton<FooBar>(typeof(IFoo), typeof(IBar));`)
3. When the app is resolving the `IBar` instance, exception is thrown

### Expected Behavior

All explicitly stated interfaces should be resolved by the container.

### Actual Behavior

The exception is thrown when resolving the dependency

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Set property 'Prism.Mvvm.ViewModelLocator.AutoWireViewModel' threw an exception.' Line number '4' and line position '9'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at PrismRegisterManySingletonRepro.Views.MainWindow.InitializeComponent() in C:\Users\juraj\source\repos\PrismRegisterManySingletonRepro\PrismRegisterManySingletonRepro\Views\MainWindow.xaml:line 1

Inner Exception 1:
ContainerResolutionException: An unexpected error occurred while resolving 'PrismRegisterManySingletonRepro.ViewModels.MainWindowViewModel'

Inner Exception 2:
ResolutionFailedException: Resolution failed with error: No public constructor is available for type PrismRegisterManySingletonRepro.Domain.IFoo.

For more detailed information run Unity in debug mode: new UnityContainer().AddExtension(new Diagnostic())

Inner Exception 3:
InvalidOperationException: No public constructor is available for type PrismRegisterManySingletonRepro.Domain.IFoo.

Inner Exception 4:
InvalidRegistrationException: Exception of type 'Unity.Exceptions.InvalidRegistrationException' was thrown.

```

### Basic Information

- Version with issue: `8.0.0.1909`,
- Last known good version: `8.0.0.1850-pre`
- Xamarin.Forms version: N/A
- IDE: Visual Studio Community 2019 version 16.7.7
- Target framework: .NET Core App 3.1 (`netcoreapp3.1`)

### Reproduction Link

- [Github repro project](https://github.com/yurislav/PrismRegisterManySingletonRepro)

**Comment by dansiegel** [comment]
@yurislav it would seem that you're probably right that the line accidentally got removed. Would you mind submitting a PR with some tests so we can catch that in the future. Thanks!

**Comment by brianlagunas** [comment]
Whoops 🤣

**Comment by yurislav** [comment]
@dansiegel Okay, I will submit the PR
