### ISSUE TITLE
[Bug] Exception on startup when using DirectoryModuleCatalog in .NET 5.0 single-file WPF application

### ISSUE THREAD

**Issue by McMarz** [PrismLibrary/Prism#2254]
### Description

Hello, this is my first time reporting an issue on GitHub. My apologies if I'm doing something wrong.

I wrote a WPF Prism application using .NET 5.0 with modules in a directory.

When the application is published as "Self-contained" and "winx-64", then it works perfectly fine, but when I also tick the "Produce single file" checkbox, then the application crashes on startup. It doesn't matter if there are modules in the "Modules" sub-directory or not.

### Steps to Reproduce

1. Publish the attached project as "Self-contained", "winx-64" and the "Produce single file" checkbox ticked.
2. Create a "Modules" sub-directory.
3. Start the application.

### Expected Behavior

The application should start and load modules from the "Modules" sub-directory if they are available.

### Actual Behavior

The application crashes on startup with an exception.

The Windows Event Viewer shows the following exception:

Application: TestApplication.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: There was an error loading assemblies.
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at Prism.Modularity.DirectoryModuleCatalog.InnerLoad()
   --- End of inner exception stack trace ---
   at Prism.Modularity.DirectoryModuleCatalog.InnerLoad()
   at Prism.Modularity.ModuleCatalogBase.Load()
   at Prism.Modularity.ModuleCatalogBase.Initialize()
   at Prism.Modularity.ModuleManager.Run()
   at Prism.PrismInitializationExtensions.RunModuleManager(IContainerProvider containerProvider)
   at Prism.PrismApplicationBase.InitializeModules()
   at Prism.PrismApplicationBase.Initialize()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TestApplication.App.Main()

### Basic Information

- Version with issue: 8.0.0.1909
- IDE: VS2019

### Reproduction Link

[TestApplication.zip](https://github.com/PrismLibrary/Prism/files/5561034/TestApplication.zip)

**Comment by brianlagunas** [comment]
The directory catalog only works with assemblies that are on disk. If you are creating a "single file" exe then no assembly files are placed on disk. You'll want to use the code based approach to load your modules if yo place to release this way.

**Comment by McMarz** [comment]
Thank you, that makes sense.

I know that in .NET 5.0 everything is loaded from memory, but I mistakenly thought that it would still be able to load modules from a directory as well like in .NET Core 3.1.

Sorry for wasting your time.
