### ISSUE TITLE
[Bug] Dependency does not resolve when using modules but does with application type registering

### ISSUE THREAD

**Issue by DallasP9124** [PrismLibrary/Prism#2555]
### Description

Attempting to modularize my project. Currently I am registering types in the application and only have a couple services with interfaces and implementations. I created a module for each 'domain' of service(s) and added type registration there and removed registration from the application class. In the application class I register my modules. Attempting to run the application after this fails with an error saying that the service's interface cant be created due to not having a public constructor. I don't know what difference there is between registering types between a module and the application class but I presume they should work exactly the same but just segregated code.

### Steps to Reproduce

1.  Download and open the project provided
2.  Open the project in either VS or Rider
3.  Run the application in debug
4.  Observer the error

### Expected Behavior
I expect that registering types in the module would resolve the same way as registering types in the application. 

### Actual Behavior
Modules are not registering types. A difference in dependency resolution that I can't really explain, breaking the application and preventing it from starting at runtime.

This is the exception that is thrown and will reflect the reproduction project:
```
System.Windows.Markup.XamlParseException: 'Set property 'Prism.Mvvm.ViewModelLocator.AutoWireViewModel' threw an exception.' Line number '8' and line position '14'.
 ---> Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'BugApp.ViewModels.CommStatusViewModel'
 ---> Unity.ResolutionFailedException: Resolution failed with error: No public constructor is available for type BugApp.IClientComm.

For more detailed information run Unity in debug mode: new UnityContainer().AddExtension(new Diagnostic())
 ---> System.InvalidOperationException: No public constructor is available for type BugApp.IClientComm.
 ---> Unity.Exceptions.InvalidRegistrationException: Exception of type 'Unity.Exceptions.InvalidRegistrationException' was thrown.
   --- End of inner exception stack trace ---
   at Unity.Processors.ConstructorProcessor.<>c.<GetResolver>b__15_1(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_2(BuilderStrategy[] chain, BuilderContext& context)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name)
   at Unity.Builder.BuilderContext.Resolve(ParameterInfo parameter, Object value)
   at Unity.Processors.ParametersProcessor`1.<>c__DisplayClass7_0.<CreateParameterResolvers>b__0(BuilderContext& context)
   at Unity.Processors.ConstructorProcessor.<>c__DisplayClass16_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_1(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.<>c.<.ctor>b__73_1(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Prism.Unity.UnityContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   --- End of inner exception stack trace ---
   at Prism.Unity.UnityContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   at Prism.Unity.UnityContainerExtension.Resolve(Type type)
   at Prism.PrismInitializationExtensions.<>c.<ConfigureViewModelLocator>b__0_0(Object view, Type type)
   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(Object view, Action`2 setDataContextCallback)
   at Prism.Mvvm.ViewModelLocator.AutoWireViewModelChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at BugApp.Views.CommStatusView.InitializeComponent() in E:\cs\PrismModuleBug\BugApp\Views\CommStatusView.xaml:line 1
   at BugApp.Views.CommStatusView..ctor() in E:\cs\PrismModuleBug\BugApp\Views\CommStatusView.xaml.cs:line 9
```

### Basic Information

- Version with issue:
  - Prism.Core, Prism.Wpf, Prism.Unity 8.1.97
- Last known good version: Unknown
- Xamarin.Forms version: N/A
- IDE: Rider 2021.2.1

### Reproduction Link
This is a link to the project zip file in OneDrive:

https://1drv.ms/u/s!AkmVnVs9ybCR3UxFi0hGudTdWlc8?e=p7iQpu

**Comment by brianlagunas** [comment]
Based on your description, you are probably injecting the services before they have been registered. The shell is shown before modules are loaded. So if you are using services when the shell is shown, but have not registered them, then you will get these exceptions.

**Comment by DallasP9124** [comment]
That really doesn't explain to me what I am doing wrong @brianlagunas . Based  on the lifecycle description in the documentation, it does not mention any other requirements other than register your modules in the application class and registering your services in the modules. So what am I actually doing wrong here?

**Comment by brianlagunas** [comment]
You are registering services in your modules which you are trying to use in the Shell. The Shell is shown before the modules are loaded, therefore your services are not registered yet.

**Comment by DallasP9124** [comment]
So then where am I supposed to register them? I don't get it, with such a simple example case provided can you not just explain maybe how I can resolve this?

**Comment by brianlagunas** [comment]
I was hoping it was clear based on the description of the issue. If your shell needs services, then you need to register them in the app, not a module.

**Comment by DallasP9124** [comment]
Assume that people asking are not seasoned veterans of Prism and know everything about the lifecycle of the framework... Thanks for your help.

**Comment by brianlagunas** [comment]
You don't have to be a seasoned veteran of Prism to know that if you are trying to use services, they need to be registered before you use them. Since I explained you were registering them too late, I assumed you would know to register them earlier.

I apologize.

**Comment by DallasP9124** [comment]
Not all frameworks have a two tier dependency resolution like this. Others I have worked with in the past don't do that but resolve the dependency tree before the application really starts so that things like this don't happen. The concept of a shell is new to me as well. That is more of what I was getting at, Prism does things differently than other frameworks.
