### ISSUE TITLE
 exception module declared a dependency, two modules load via directory loading one module dependent on other, ModuleDependencyattribute useda

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2747]
### Description

I am using  .Net 6, Visual 2022, and the latest vision of PRISM
I am getting an exception when doing navigation of a view in one module into a region name in another module.
Both modules are directory loading.
The ModuleDependency Attribute is on the module where the navigated view is located and the is set the module which containsthe region the view is is places,e
The exact exception is
08:58:20 ERR] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModularityException: A module declared a dependency on another module which is not declared to be loaded. Missing module(s): SuperUserStatusModule

SuperUserStatusModule is the module project that contains the 
Here is that module's class
    [Module(ModuleName = SuperUserModuleNames.ModuleStatus)]
    public class SuperUserStatusModule : IModule

SuperUserStatusCollectionModule is the module that contains the navigation view which is places in the region in the SuperUserStatusModule 
Here is that module's class
    [Module(ModuleName = SuperUserModuleNames.ModuleStatusCollection)]
    [ModuleDependency(SuperUserModuleNames.ModuleStatus)]
    public class SuperUserStatusCollectionModule : IModule

I have attached the two module classes if necessary I can make a simple project. 
I have googles and tried and search for an example the used two modules via directory loading where one module is dependent on the other where a navigation view in one module , is place in a region in another view and as usual there was nothing. Closed I found was the ModularityWithUnity  source code from PRISM 5 which is great code but the exception still occurs
[SuperUserStatusCollectionModule.zip](https://github.com/PrismLibrary/Prism/files/9394647/SuperUserStatusCollectionModule.zip)

### Steps to Reproduce

See documentation alone

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08:58:20 ERR] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModularityException: A module declared a dependency on another module which is not declared to be loaded. Missing module(s): SuperUserStatusModule
   at Prism.Modularity.ModuleDependencySolver.Solve()
   at Prism.Modularity.ModuleCatalogBase.ValidateDependencyGraph()
   at Prism.Modularity.ModuleCatalogBase.Validate()
   at Super.User.App.AggregateModuleCatalog.Initialize() in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\AggregateModuleCatalog.cs:line 106
   at Prism.Modularity.ModuleManager.Run()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by stevensrf11** [comment]
Just delete this comment i have a different bug to post
