### ISSUE TITLE
Exception load navigating a view in one module to region name in another module

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2749]
### Description

I am using .Net 6 , Visual Studio 2022, latest version of PRISM
I am getting an exception when doing navigation of a view in one module into a region name in another module.
I have attached the module files below along with the use control that contains the region.
The exception is I believe on the navigation path or it might be on where the ModuleDepenendency attribute as place.
I have never gotten the full name of the navigation path ever to work, I have always had to the name of the view as the navigation path to work
Both modules are directory loading.
The ModuleDependency Attribute is on the module where the navigated view is located and is set to module which contains the region the view is placed

Exception that occurs
09:43:03 FTL] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModuleInitializeException: An exception occurred while initializing module 'SuperUserStatusCollectionModule'.
    - The exception message was: Object reference not set to an instance of an object.
    - The Assembly that the module was trying to be loaded from was:Super.User.Status.Collection.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationCompleted(NavigationResult result)
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationToStatusUserControl()
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   --- End of inner exception stack trace ---
   at Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   at Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[09:43:03 ERR] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModuleInitializeException: An exception occurred while initializing module 'SuperUserStatusCollectionModule'.
    - The exception message was: Object reference not set to an instance of an object.
    - The Assembly that the module was trying to be loaded from was:Super.User.Status.Collection.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationCompleted(NavigationResult result)
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationToStatusUserControl()
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   --- End of inner exception stack trace ---
   at Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   at Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[SuperUserStatusCollectionModule.zip](https://github.com/PrismLibrary/Prism/files/9394998/SuperUserStatusCollectionModule.zip)

### Steps to Reproduce

See Description

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell
I am using .Net 6 , Visual Studio 2022, latest version of PRISM
I am getting an exception when doing navigation of a view in one module into a region name in another module.
I have attached the module files below along with the use control that contains the region.
The exception is I believe on the navigation path or it might be on where the ModuleDepenendency attribute as place.
I have never gotten the full name of the navigation path ever to work, I have always had to the name of the view as the navigation path to work
Both modules are directory loading.
The ModuleDependency Attribute is on the module where the navigated view is located and is set to module which contains the region the view is placed


Exception that occurs
09:43:03 FTL] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModuleInitializeException: An exception occurred while initializing module 'SuperUserStatusCollectionModule'.
    - The exception message was: Object reference not set to an instance of an object.
    - The Assembly that the module was trying to be loaded from was:Super.User.Status.Collection.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationCompleted(NavigationResult result)
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationToStatusUserControl()
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   --- End of inner exception stack trace ---
   at Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   at Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[09:43:03 ERR] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModuleInitializeException: An exception occurred while initializing module 'SuperUserStatusCollectionModule'.
    - The exception message was: Object reference not set to an instance of an object.
    - The Assembly that the module was trying to be loaded from was:Super.User.Status.Collection.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationCompleted(NavigationResult result)
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationToStatusUserControl()
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   --- End of inner exception stack trace ---
   at Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   at Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by stevensrf11** [comment]
Just delete this one two 
I am getting still getting exception but just not listing the issue right
