### ISSUE TITLE
Exception when navigation view in one module to region in another module, both modules loaded by directory

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2750]
### Description

I am using .Net 6 , Visual Studio 2022, latest version of PRISM
I am getting an exception when doing navigation of a view in one module into a region name in another module.
I have attached the module files below along with the use control that contains the region.
The exception is I believe on the navigation path or it might be on where the ModuleDepenendency attribute as place.
I have never gotten the full name of the navigation path ever to work, I have always had to the name of the view as the navigation path to work
Both modules are directory loading.
The ModuleDependency Attribute is on the module where the navigated view is located and is set to module which contains the region the view is placed
The module in the module project which contains the named region is loaded first
Next the module in the module project which contains the navigation view is loaded
When I try to navigation to the region name in the moudle project which contains the navigation view the excpetion thrown
Here is the module class which contains the region the view is navigated to
  [Module(ModuleName = SuperUserModuleNames.ModuleStatus)]
    public class SuperUserStatusModule : IModule
    {

Here is the module class  contains the navigation view
     
    [Module(ModuleName = SuperUserModuleNames.ModuleStatusCollection)]
 [ModuleDependency(SuperUserModuleNames.ModuleStatus)]
    public class SuperUserStatusCollectionModule : IModule
    {

Here is the module class which contains the region the view is navigated to
  [Module(ModuleName = SuperUserModuleNames.ModuleStatus)]
[StatusCollectionUserControl.xaml.zip](https://github.com/PrismLibrary/Prism/files/9395156/StatusCollectionUserControl.xaml.zip)
    public class SuperUserStatusModule : IModule
    {

here is the request navigation call in this class where the exception is thrown
            _regionManager.RequestNavigate(RegionNames.RegionStatusCollection, "StatusCollectionUserControl", NavigationCompleted, parameters);

### Steps to Reproduce

I run the code when calling the requestnavigate method in the module class in the project that contains the navigation view exception is thrown

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell
[10:12:22 FTL] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModuleInitializeException: An exception occurred while initializing module 'SuperUserStatusCollectionModule'.
    - The exception message was: Object reference not set to an instance of an object.
    - The Assembly that the module was trying to be loaded from was:Super.User.Status.Collection.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationCompleted(NavigationResult result)
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationToStatusUserControl()
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   --- End of inner exception stack trace ---
   at Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   at Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[10:12:22 ERR] Unhandled exception in Super.User.App v1.0.0.0 <s:>
Prism.Modularity.ModuleInitializeException: An exception occurred while initializing module 'SuperUserStatusCollectionModule'.
    - The exception message was: Object reference not set to an instance of an object.
    - The Assembly that the module was trying to be loaded from was:Super.User.Status.Collection.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationCompleted(NavigationResult result)
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.NavigationToStatusUserControl()
   at Super.User.Status.Collection.Module.SuperUserStatusCollectionModule.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   --- End of inner exception stack trace ---
   at Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   at Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   at Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Super.User.App.SuperUserApp.OnStartup(StartupEventArgs e) in C:\accu\source\SuperUserPOC\SuperUser\Super.User.App\SuperUserApp.xaml.cs:line 127
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by brianlagunas** [comment]
You must provide an app that reproduces the error or this issue will be closed.
