### ISSUE TITLE
[BUG] MAUI With PRISM 

### ISSUE THREAD

**Issue by LaBoss** [PrismLibrary/Prism#2913]
### Description

Hello i develop entire app with prism on MAUI, i use Prism.DryIoc.Maui  Version 8.1.273-pre

In debug mode the app runs nice, but in realse the app open then close automatic with erro bellow.

Any hits?

My startup code is

`    public static MauiApp CreateMauiApp()
    {

        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UsePrism(PrismStartup.Configure)
            .UseMauiCommunityToolkit()
            .UseSharpnadoTabs(false)
            .ConfigureMopups()
            .UseUraniumUI()
            .UseUraniumUIMaterial()
            .UseUraniumUIBlurs()
            .ConfigureMauiHandlers(handlers =>
            {
                handlers.AddSettingsViewHandler();
            })
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                fonts.AddFont("FontAwesome6Brands.otf", "faBrand");
                fonts.AddFont("FontAwesome6Regular.otf", "faRegular");
                fonts.AddFont("FontAwesome6Solid.otf", "faSolid");
            });

        return builder.Build();
    }`

`
internal static class PrismStartup
{
    public static void Configure(PrismAppBuilder builder)
    {
        builder.RegisterTypes(RegisterTypes)
               .ConfigureModuleCatalog(_ConfigureModules)
               .OnAppStart("Startup");

        
    }
    private static void RegisterTypes(IContainerRegistry containerRegistry)
    {
        containerRegistry.RegisterSingleton<IUser, SessionUser>()
                         .RegisterSingleton<Classes.DataBase>()
                         .RegisterForNavigation<NavigationPage>("nav")
                         .RegisterForNavigation<Startup>()
                         .RegisterForNavigation<Settings>()
                         .RegisterForNavigation<MainPage>();
    }
    private static void _ConfigureModules(IModuleCatalog catalog)
    {
        catalog.AddModule<MAUI.MDI.Authentication.AuthModule>();
               //.AddModule<CoreAppModule>(InitializationMode.OnDemand);
    }

}
`

### Steps to Reproduce

Create a app with version 8.1.273-pre

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No

### Relevant log output

```shell
07-14 15:12:35.536  5839  5839 E AndroidRuntime: FATAL EXCEPTION: main
07-14 15:12:35.536  5839  5839 E AndroidRuntime: Process: *, PID: 5839
07-14 15:12:35.536  5839  5839 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NotImplementedException: Either set MainPage or override CreateWindow.
07-14 15:12:35.536  5839  5839 E AndroidRuntime:    at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:    at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:49)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8305)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8284)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7872)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-14 15:12:35.536  5839  5839 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by LaBoss** [comment]
If i override  CreateWindow(IActivationState activationState) and add         MainPage = new Startup();

the crash is:

```
07-14 15:25:55.419  8088  8088 E AndroidRuntime: FATAL EXCEPTION: main
07-14 15:25:55.419  8088  8088 E AndroidRuntime: Process: com., PID: 8088
07-14 15:25:55.419  8088  8088 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.MissingMethodException: Method not found: Microsoft.Maui.Hosting.MauiAppBuilder Microsoft.Maui.PrismAppExtensions.UsePrism(Microsoft.Maui.Hosting.MauiAppBuilder,System.Action`1<Prism.PrismAppBuilder>)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:    at App.MainApplication.CreateMauiApp()
07-14 15:25:55.419  8088  8088 E AndroidRuntime:    at Microsoft.Maui.MauiApplication.OnCreate()
07-14 15:25:55.419  8088  8088 E AndroidRuntime:    at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7872)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-14 15:25:55.419  8088  8088 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by mshenoy83** [comment]
Try inheriting the main app in App.Xaml from PrismApplication

```
<prism:PrismApplication xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="http://prismlibrary.com"
             x:Class="MyPersonal.App">
```

**Comment by phillippschmedt** [comment]
The error message and the actual error are usually unrelated in my experience. It happens when something fails before or when navigating to the first page.
