### ISSUE TITLE
[BUG] Prism.Maui iOS app crashes on startup in release builds

### ISSUE THREAD

**Issue by tbaggett** [PrismLibrary/Prism#2987]
### Description

Launching app iOS release builds results in crash during startup. It appears to be caused by DryIoc using System.Reflection.Emit.DynamicMethod. See log output for details.

Tooling versions:
.NET 8.0.100-rc.2.23502.2
VS for Mac v17.6.6 (build 408)
Prism.DryIoc.Maui 9.0.286-pre

[Repro project](https://github.com/tbaggett/PrismMauiIosStartupCrash)

### Steps to Reproduce

1. Open provided repro project.
2. Select "Release" build configuration and an iOS Simulator device
3. Build/launch release version by executing VS for Mac's "Debug -> Start Without Debugging" command
4. App starts launching on simulator (black screen seen, then VS Application Output begins to be populated)
5. App is terminated due to Microsoft.Maui.Controls.InvalidNavigationException being thrown

App behaves as expected in iOS debug builds and Android debug or release builds. Crash originally occurred in IPA built in a DevOps pipeline and distributed to device via TestFlight prior to reproducing locally with the iOS simulator.

### Platform with bug

.NET MAUI

### Affected platforms

iOS

### Did you find any workaround?

No. I added a package reference for System.Reflection.Emit v4.7.0 in an attempt to resolve the issue, based on past Xamarin Forms solutions. It didn't change the result, but is still currently present in the repro project. I also tried using the System.Reflection.Emit.Lightweight package without resolving the issue.

### Relevant log output

```shell
42:16.634646-0500 PrismReleaseTest[52398:5971062] Exception occurred!
  Message: An error occurred while resolving the page. This is most likely the result of invalid XAML or other type initialization exception
  Stacktrace:    at Prism.Navigation.PageNavigationService.CreatePage(String segmentName)
2023-10-25 12:42:16.635010-0500 PrismReleaseTest[52398:5971062]    at Prism.Navigation.PageNavigationService.CreatePageFromSegment(String segment)
2023-10-25 12:42:16.636111-0500 PrismReleaseTest[52398:5971062]    at Prism.Navigation.PageNavigationService.UseReverseNavigation(Page currentPage, String nextSegment, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated)
   at Prism.Navigation.PageNavigationService.ProcessNavigationForNavigationPage(NavigationPage currentPage, String nextSegment, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated)
2023-10-25 12:42:16.636249-0500 PrismReleaseTest[52398:5971062]    at Prism.Navigation.PageNavigationService.ProcessNavigation(Page currentPage, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated)
2023-10-25 12:42:16.636304-0500 PrismReleaseTest[52398:5971062]    at Prism.Navigation.PageNavigationService.ProcessNavigationForRootPage(String nextSegment, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated)
2023-10-25 12:42:16.636495-0500 PrismReleaseTest[52398:5971062]    at Prism.Navigation.PageNavigationService.ProcessNavigation(Page currentPage, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated)
   at Prism.Navigation.PageNavigationService.NavigateAsync(Uri uri, INavigationParameters parameters)
2023-10-25 12:42:16.636775-0500 PrismReleaseTest[52398:5971062] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023-10-25 12:42:16.639149-0500 PrismReleaseTest[52398:5971062] Inner Exception:
  Message: PlatformNotSupported_ReflectionEmit
  Stacktrace:    at System.Reflection.Emit.AssemblyBuilder.ThrowDynamicCodeNotSupported()
   at System.Reflection.Emit.AssemblyBuilder.EnsureDynamicCodeSupported()
2023-10-25 12:42:16.639225-0500 PrismReleaseTest[52398:5971062]    at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod)
2023-10-25 12:42:16.639293-0500 PrismReleaseTest[52398:5971062]    at System.Reflection.Emit.DynamicMethod..ctor(String name, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
2023-10-25 12:42:16.639357-0500 PrismReleaseTest[52398:5971062]    at DryIoc.FastExpressionCompiler.LightExpression.ExpressionCompiler.CompileNoArgsNew(ConstructorInfo ctor, Type delegateType, Type[] closurePlusParamTypes, Type returnType)
   at DryIoc.FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCompileNestedLambda(NestedLambdaInfo nestedLambdaInfo, CompilerFlags setup)
2023-10-25 12:42:16.639419-0500 PrismReleaseTest[52398:5971062]    at DryIoc.FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCompileBoundToFirstClosureParam(Type delegateType, Expression bodyExpr, IParameterProvider paramExprs, Type[] closurePlusParamTypes, Type returnType, CompilerFlags flags)
2023-10-25 12:42:16.639488-0500 PrismReleaseTest[52398:5971062]    at DryIoc.FactoryDelegateCompiler.CompileToFactoryDelegate(Expression expression, Boolean preferInterpretation)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[ContainerProviderLocator](IResolver resolver, IfUnresolved ifUnresolved)
2023-10-25 12:42:16.639545-0500 PrismReleaseTest[52398:5971062]    at Prism.Container.DryIoc.DryIocScopedProvider..ctor(IResolverContext resolver)
   at Prism.Container.DryIoc.DryIocContainerExtension.CreateScopeInternal()
   at Prism.Container.DryIoc.DryIocContainerExtension.CreateScope()
   at Prism.Navigation.PageNavigationService.CreatePage(String segmentName)
2023-10-25 12:42:16.639661-0500 PrismReleaseTest[52398:5971062] ------------------------------------------------------------------------------------------------------------------------------------
2023-10-25 12:42:16.681361-0500 PrismReleaseTest[52398:5971062] *** Terminating app due to uncaught exception 'Microsoft.Maui.Controls.InvalidNavigationException', reason: 'Expected Navigation Failed. No Root Window has been created. (Microsoft.Maui.Controls.InvalidNavigationException)
   at Prism.Navigation.PrismWindowManager.CreateWindow(Application app, IActivationState activationState)
   at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
```

**Comment by dansiegel** [comment]
This will be addressed in the next public release. In the mean time to fix this issue be sure to update the Default Rules with `WithUseInterpretation()`

```cs
builder.UsePrism(DryIocContainerExtension.DefaultRules.WithUseInterpretation(), prism => prism....)
```

**Comment by tbaggett** [comment]
A workaround that fixes the issue was suggested by the DryIoc author. This code prevents the crash in iOS release builds.

`		var builder = MauiApp.CreateBuilder();
		builder
        .UseMauiApp<App>()
            .UsePrism(global::Prism.Container.DryIoc.DryIocContainerExtension.DefaultRules.WithUseInterpretation(), prism =>
                prism.RegisterTypes(containerRegistry =>
                {
                    containerRegistry.RegisterForNavigation<MainPage, MainViewModel>();
                })
                .OnAppStart((containerProvider, navigationService) =>
                    navigationService.CreateBuilder()
                                     .AddNavigationPage()
                                     .AddSegment<MainViewModel>()
                                     .NavigateAsync(OutputExceptionToConsole)
                )
			)
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });
`
