### ISSUE TITLE
Delegate RaiseCanExecuteChanged XML comments unclear

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#299]
The XML comments on the DelegateCommand.RaiseCanExecuteChanged method are misleading.  Currently reads:

_Raises Prism.Commands.DelegateCommandBase.CanExecuteChanged on the UI thread so every command invoker can requery to check if the command can execute._

The delegate command does not force the call to be made on the UI thread.  The call to this method should be made on the UI thread, but the DelegateCommand does nothing internally to make sure it will invoke on the UI thread.  So if you try to make this call on a separate thread, it will throw an exception.

```
public MainWindowViewModel()
    {
        TestCommand = new DelegateCommand(Test, CanTest);

        ActionCommand = new DelegateCommand(() =>
        {
            Task.Run(() =>
            {
                Thread.Sleep(1000);
                TestCommand.RaiseCanExecuteChanged();
            });
        });
    } 
```

**Comment by briannoyes** [comment]
I may be remembering wrong, but I think the command code used to do something with the Dispatcher and we got rid of that or changed it when we pulled it into a PCL. So that is probably where the comment came from, but agree it is wrong at this point.

**Comment by brianlagunas** [comment]
Ohhh... It did!  Back in v2.  In v2.2 it looks like it was removed.

**Comment by briannoyes** [comment]
Wow, didn't realize it was that far back. And this would be why some people say commenting code is a bad thing because it almost never gets updated when the code changes. :) I'm not one of those though, especially with the tooling around doc comments these days.

**Comment by federom** [comment]
How should i execute the RaiseCanExecuteChanged method from the View Model ?

Thanks!

**Comment by brianlagunas** [comment]
Just call Command.RaiseCanExecuteChanged() when you need to requery it.

**Comment by federom** [comment]
Thanks Brian!

I used to do it in that way in Prism 4. The issue is that i updated to Prism 6 using the Nuget packages and when i try to execute the RaiseCanExecuteChanged method I received the following exception:

`
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The calling thread cannot access this object because a different thread owns it.
  Source=WindowsBase
  StackTrace:
       at System.Windows.Threading.Dispatcher.VerifyAccess()
       at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
       at System.Windows.Controls.Primitives.ButtonBase.get_Command()
       at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
       at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
       at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
`

Any clue how should i call it from the proper thread?

Thanks again!

**Comment by brianlagunas** [comment]
Nothing changed from Prism 4 to Prism 6 in regards to the execution of a delegate command.  It appears you are trying to make the call on a separate thread.  You should use the dispatcher to raise the method on the UI thread in which the command was created.

**Comment by federom** [comment]
Thanks Brian,

For some reason since I upgraded i started to receive those exceptions.

Now i am using 
`Dispatcher.CurrentDispatcher.BeginInvoke((Action)(() =>{Command.RaiseCanExecuteChanged()  }));`

in order to avoid that exception

**Comment by tinyplasticgreyknight** [comment]
@brianlagunas I believe the threading behaviour changed in commit f44507fdcc38194d977971931bbfb693b3c5906f.  `WeakEventHandlerManager` used to run the handlers inside a `SynchronizationContext`, but this is no longer the case.

**Comment by brianlagunas** [comment]
Yes, start a new issue addressing your topic.  This issue is related to XML comments.  If this is related simply mention this issue in your new issue.

**Comment by brianlagunas** [comment]
@federom your issue has been fixed. You can now make calls RaiseCanExecuteChanged on a background thread and it will work.
