### ISSUE TITLE
[BUG] Android app crashes on startup in release mode (MAUI)

### ISSUE THREAD

**Issue by Alex-Dobrynin** [PrismLibrary/Prism#3020]
### Description

When building MAUI android project in .NET8 using prism version 9.0.271-pre (latest available on nuget) app crashes on startup.

message: Unable to select a single public constructor from the implementation type 'Prism.Ioc.Internals.ContainerProviderLocator' because the type does not have public constructors.

message: Unable to select a single public constructor from the implementation type 'Prism.PrismInitializationService' because the type does not have public constructors.

Playing with proguard configuration and with different settings in android section of project settings doesn't help

Repro project:
[PrismAndroidCrash.zip](https://github.com/PrismLibrary/Prism/files/13526996/PrismAndroidCrash.zip)

### Steps to Reproduce

1. Open repro project
2. Choose release configuration and device
3. Click Play button in VS
4. Open logcat and wait until app build and run

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

nope

### Relevant log output

```shell
first crash log
12-01 12:51:19.233  3186  3186 D AndroidRuntime: Shutting down VM
12-01 12:51:19.233  3186  3186 E AndroidRuntime: FATAL EXCEPTION: main
12-01 12:51:19.233  3186  3186 E AndroidRuntime: Process: com.companyname.prismandroidcrash, PID: 3186
12-01 12:51:19.233  3186  3186 E AndroidRuntime: android.runtime.JavaProxyThrowable: [DryIoc.ContainerException]: code: Error.UnableToSelectSinglePublicConstructorFromNone;
12-01 12:51:19.233  3186  3186 E AndroidRuntime: message: Unable to select a single public constructor from the implementation type 'Prism.Ioc.Internals.ContainerProviderLocator' because the type does not have public constructors.
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at DryIoc.Throw.When(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at DryIoc.ReflectionFactory.ValidateAndNormalizeRegistration(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at DryIoc.Container.Register(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at DryIoc.Registrator.Register(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at DryIoc.Registrator.Register(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Prism.Container.DryIoc.DryIocContainerExtension..ctor(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Prism.Container.DryIoc.DryIocContainerExtension..ctor(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Prism.Container.DryIoc.DryIocContainerExtension..ctor(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Microsoft.Maui.PrismAppExtensions.UsePrism(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at PrismAndroidCrash.MauiProgram.CreateMauiApp(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at PrismAndroidCrash.MainApplication.CreateMauiApp(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Microsoft.Maui.MauiApplication.OnCreate(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Android.App.Application.n_OnCreate(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(SourceFile:1)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8177)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-01 12:51:19.233  3186  3186 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

another crash log
12-01 13:34:48.975  4566  4566 D AndroidRuntime: Shutting down VM
12-01 13:34:48.975  4566  4566 E AndroidRuntime: FATAL EXCEPTION: main
12-01 13:34:48.975  4566  4566 E AndroidRuntime: Process: com.companyname.prismandroidcrash, PID: 4566
12-01 13:34:48.975  4566  4566 E AndroidRuntime: android.runtime.JavaProxyThrowable: [DryIoc.ContainerException]: code: Error.UnableToSelectSinglePublicConstructorFromNone;
12-01 13:34:48.975  4566  4566 E AndroidRuntime: message: Unable to select a single public constructor from the implementation type 'Prism.PrismInitializationService' because the type does not have public constructors.
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at DryIoc.Throw.When(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at DryIoc.ReflectionFactory.ValidateAndNormalizeRegistration(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at DryIoc.Container.Register(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Prism.Container.DryIoc.DryIocContainerExtension.RegisterSingleton(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Prism.Ioc.IContainerRegistryExtensions.RegisterSingleton(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Prism.PrismAppBuilder..ctor(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Prism.PrismAppBuilderExtensions.UsePrism(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Microsoft.Maui.PrismAppExtensions.UsePrism(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at PrismAndroidCrash.MauiProgram.CreateMauiApp(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at PrismAndroidCrash.MainApplication.CreateMauiApp(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Microsoft.Maui.MauiApplication.OnCreate(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Android.App.Application.n_OnCreate(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(SourceFile:1)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8177)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-01 13:34:48.975  4566  4566 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by dansiegel** [comment]
This is because you've enabled linking. You'll want to add a [linker configuration](https://learn.microsoft.com/en-us/dotnet/maui/android/linking?view=net-maui-8.0&tabs=vs#preserve-assemblies-types-and-members) to preserve members from Prism.Maui and likely other dependencies you have.

**Comment by dharamhbtik** [comment]
I am also experiencing the same and my  linking is disabled in my case.
