### ISSUE TITLE
[BUG][MAUI] EventToCommandBehavior with RelativeSource binding throws InvalidOperationException

### ISSUE THREAD

**Issue by anpin** [PrismLibrary/Prism#3063]
### Description

EventToCommandBehavior with RelativeSource binding throws InvalidOperationException. 

The exception is thrown at this [1] line and it seems that `targetObject` which is an instance of `EventToCommandBehavior` can not be cast to an `Element`
[1] https://github.com/dotnet/maui/blob/0ef0c03976f0fc01306e209fa2edbcb13c9181df/src/Controls/src/Core/Binding.cs#L152

### Steps to Reproduce

```
<Picker 
    x:Name="mirrorModePicker"
    ItemsSource="{Binding Path=MirrorModes, Source={RelativeSource AncestorType={x:Type a:IEditConnectors}, Mode=FindAncestorBindingContext }}" 
    SelectedItem="{Binding MirrorMode, Converter={StaticResource RotationConverter}}"
    ItemDisplayBinding="{Binding Name}"
   >
    <Picker.Behaviors>
      <prism:EventToCommandBehavior 
        EventName="SelectedIndexChanged"
          Command="{Binding SetRotationCommand, Source={RelativeSource AncestorType={x:Type a:IEditConnectors}, Mode=FindAncestorBindingContext }}"  
          EventArgsConverter="{StaticResource RotationChangedEventArgsConverter}"
          EventArgsConverterParameter="{x:Reference mirrorModePicker}"
          />
    </Picker.Behaviors>
  </Picker>
```

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Windows

### Did you find any workaround?

not yet

### Relevant log output

```shell
[11:59:39 ERR] Operation is not valid due to the current state of the object.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Maui.Controls.Binding.ApplyRelativeSourceBinding(BindableObject targetObject, BindableProperty targetProperty, SetterSpecificity specificity)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Operation is not valid due to the current state of the object. Operation is not valid due to the current state of the object.    at Microsoft.Maui.Controls.Binding.ApplyRelativeSourceBinding(BindableObject targetObject, BindableProperty targetProperty, SetterSpecificity specificity)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by dansiegel** [comment]
thank you for the report @anpin however a reproduction sample is required. Please be sure to update this issue with a reproduction.

**Comment by dansiegel** [comment]
@anpin out of curiosity... was this code from a migrated Xamarin.Forms app? I'm curious if this was working previously in Xamarin.Forms

**Comment by carlosxjose** [comment]
Sounds you've been busy @brianlagunas .... I've received about 15 emails from yersterday afternoon... 👍

**Comment by brianlagunas** [comment]
HAHA!! Yup. I got a break in my day job to start knocking some of these bugs out.

I'm on a roll 😄
