### ISSUE TITLE
[BUG] An unhandled exception of type 'Microsoft.Maui.Controls.InvalidNavigationException' occurred in Mono.Android.Runtime.dll: 'Expected Navigation Failed. No Root Window has been created.'

### ISSUE THREAD

**Issue by Jay-57blocks** [PrismLibrary/Prism#3275]
### Description

<img width="1859" alt="image" src="https://github.com/user-attachments/assets/834efa1f-0a57-4bb7-9594-0a4789fc67b0">

Hi, 

I found a strange problem, when I run the project, I occasionally encounter the exception "A dependency issue occurred while resolving the ViewModel. check the InnerException for the ContainerResolutionException", but when I end the run and run the project again, the exception disappears, I didn't change any code or configuration, very strange problem, looking forward to receive your reply. Thank you.

### Steps to Reproduce

This problem is occasional, only encountered occasionally when starting a project

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No

### Relevant log output

```shell
------------------------------------------------------------------------------
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.DiagnosticSource.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Diagnostics.DiagnosticSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Requests.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Net.Requests.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.RecyclerView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CardView.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Xamarin.AndroidX.RecyclerView.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Xamarin.AndroidX.CardView.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CoordinatorLayout.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Xamarin.AndroidX.CoordinatorLayout.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.Primitives.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly Lottie.Android.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Lottie.Android.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly DevExpress.Maui.Charts.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/DevExpress.Maui.Charts.dll'. Module was built without symbols.
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.HotReload.Forms.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Microsoft.Maui.Controls.HotReload.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Drawing.Common.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Drawing.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[m.twe.elon.test] Explicit concurrent mark compact GC freed 184286(13MB) AllocSpace objects, 29(836KB) LOS objects, 65% free, 3231KB/9375KB, paused 92us,1.076ms total 17.128ms
[monodroid-assembly] open_from_bundles: failed to load assembly mscorlib.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[TrafficStats] tagSocket(6) with statsTag=0xd83ddc19, statsUid=-1
[OpenGLRenderer] HWUI - treat SMPTE_170M as sRGB
[libMEOW] meow new tls: 0xb40000768aaf6cc0
[libc] Access denied finding property "ro.vendor.mtk.gpu.glt"
[libMEOW] meow reload base cfg path: na
[libMEOW] meow reload overlay cfg path: na
[QT] [QT]file does not exist
[libMEOW] applied 1 plugins for [com.twe.elon.test]:
[libMEOW]   plugin 1: [libMEOW_gift.so]: 0xb40000767ee37180
[libMEOW] rebuild call chain: 0xb40000768ab12980
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Loader.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Xamarin.AndroidX.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[AppCompatDelegate] Checking for metadata for AppLocalesMetadataHolderService : Service not found
[monodroid-assembly] open_from_bundles: failed to load assembly _Microsoft.Android.Resource.Designer.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/_Microsoft.Android.Resource.Designer.dll'. Module was built without symbols.
[10:40:05 WRN] [AppOnAppStart] Onboarding_0
[10:40:05 INF] 2024-11-06:02:40:05.867: TraceWarning : [AppOnAppStart] Onboarding_0
[10:40:05 INF] 2024-11-06:02:40:05.908: TraceNavigation NavigationPage/DebugDashBoard
[10:40:06 INF] 2024-11-06:02:40:06.104: TracePower LimitedBattery
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[monodroid-assembly] open_from_bundles: failed to load assembly Newtonsoft.Json.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Formatters.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Runtime.Serialization.Formatters.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Numerics.dll
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[monodroid-assembly] open_from_bundles: failed to load assembly System.Data.Common.dll
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
UNMC.dll: Loaded '/Users/57block/Documents/TWE/unmc/src/UNMC/UNMC/UNMC/obj/Debug/net8.0-android/android/assets/System.Data.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[MediaPlayerNative] setDataSource(IDataSource)
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[10:40:07 INF] 2024-11-06:02:40:07.209: TraceInfo :
Exception thrown: 'System.NullReferenceException' in UNMC.dll
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[10:40:16 ERR] NavigateTo(NavigationPage/DebugDashBoard, navigationParameters: ?animated=False) failed
Prism.Navigation.NavigationException: A dependency issue occurred while resolving the ViewModel. Check the InnerException for the ContainerResolutionException
 ---> Prism.Mvvm.ViewModelCreationException: Unable to Create ViewModel for 'UNMC.Views.Setup.DebugDashBoard'.
 ---> Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'UNMC.ViewModels.Setup.DebugDashBoardViewModel'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Object& result) in /_/src/DryIoc/Container.cs:line 3052
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 555
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 466
   at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType, Object[] args, IfUnresolved ifUnresolved, Type requiredServiceType, Object serviceKey) in /_/src/DryIoc/Container.cs:line 8652
   at Prism.Container.DryIoc.DryIocScopedProvider.Resolve(Type type, ValueTuple`2[] parameters) in /_/src/Prism.Container.DryIoc/DryIocScopedProvider.cs:line 54
   --- End of inner exception stack trace ---
   at Prism.Container.DryIoc.DryIocScopedProvider.Resolve(Type type, ValueTuple`2[] parameters) in /_/src/Prism.Container.DryIoc/DryIocScopedProvider.cs:line 58
   at Prism.Container.DryIoc.DryIocScopedProvider.Resolve(Type type) in /_/src/Prism.Container.DryIoc/DryIocScopedProvider.cs:line 41
   at Prism.PrismAppBuilder.DefaultViewModelLocator(Object view, Type viewModelType) in D:\a\Prism\Prism\src\Maui\Prism.Maui\PrismAppBuilder.cs:line 114
   --- End of inner exception stack trace ---
   at Prism.PrismAppBuilder.DefaultViewModelLocator(Object view, Type viewModelType) in D:\a\Prism\Prism\src\Maui\Prism.Maui\PrismAppBuilder.cs:line 118
   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(Object view, Action`2 setDataContextCallback) in D:\a\Prism\Prism\src\Prism.Core\Mvvm\ViewModelLocationProvider.cs:line 135
   at Prism.Mvvm.ViewModelLocator.Autowire(Object view) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Mvvm\ViewModelLocator.cs:line 75
   at Prism.Mvvm.ViewRegistryBase.Autowire(BindableObject view) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Mvvm\ViewRegistryBase.cs:line 18
   at Prism.Mvvm.ViewRegistryBase`1[[Microsoft.Maui.Controls.BindableObject, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateView(IContainerProvider container, String name) in D:\a\Prism\Prism\src\Prism.Core\Mvvm\ViewRegistryBase{TBaseView}.cs:line 57
   at Prism.Navigation.PageNavigationService.CreatePage(String segmentName) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 775
   --- End of inner exception stack trace ---
   at Prism.Navigation.PageNavigationService.CreatePage(String segmentName) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 792
   at Prism.Navigation.PageNavigationService.CreatePageFromSegment(String segment) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 815
   at Prism.Navigation.PageNavigationService.UseReverseNavigation(Page currentPage, String nextSegment, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 1006
   at Prism.Navigation.PageNavigationService.ProcessNavigationForNavigationPage(NavigationPage currentPage, String nextSegment, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 506
   at Prism.Navigation.PageNavigationService.ProcessNavigation(Page currentPage, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 368
   at Prism.Navigation.PageNavigationService.ProcessNavigationForRootPage(String nextSegment, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 465
   at Prism.Navigation.PageNavigationService.ProcessNavigation(Page currentPage, Queue`1 segments, INavigationParameters parameters, Nullable`1 useModalNavigation, Boolean animated) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 358
   at Prism.Navigation.PageNavigationService.NavigateAsync(Uri uri, INavigationParameters parameters) in D:\a\Prism\Prism\src\Maui\Prism.Maui\Navigation\PageNavigationService.cs:line 305
[10:40:17 INF] 2024-11-06:02:40:17.050: TraceError : NavigateTo(NavigationPage/DebugDashBoard, navigationParameters: ?animated=False) failed : A dependency issue occurred while resolving the ViewModel. Check the InnerException for the ContainerResolutionException
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
[MediaPlayerNative] message received msg=200, ext1=10973, ext2=0
[MediaPlayerNative] info/warning (10973, 0)
[MediaPlayerNative] message received msg=1, ext1=0, ext2=0
[MediaPlayerNative] MediaPlayer::notify() prepared
[MediaPlayerNative] signal application thread
[MediaPlayerNative] prepare complete - status=0
[MediaPlayerNative] invoke 80
[MediaPlayerNative] invoke 76
[MediaPlayer-JNI] native_setup
[MediaPlayerNative] constructor
[MediaPlayerNative] setListener
[MediaPlayer-JNI] get_session_id()
[MediaPlayerNative] setDataSource(IDataSource)
Exception thrown: 'System.NullReferenceException' in UNMC.dll
[MediaPlayerNative] setVideoSurfaceTexture
[MediaPlayerNative] prepare
```

```
<PackageReference Include="Prism.DryIoc.Maui" Version="9.0.218-pre" />
<PackageReference Include="Prism.Maui" Version="9.0.218-pre" />
```
```

**Comment by muak** [comment]
I too am facing this issue.

**Comment by dansiegel** [comment]
This is an error within your own code. The error you are seeing is telling you that the navigation failed. You need to check the Navigation Result. This will help point to what the underlying problem is. If the inner exception is a ContainerResolutionException you can call GetErrors to see a map of the errors or you can call GetRootError to try to get to a Root Exception. This will help you to further identify the actual source of your issue.
