### ISSUE TITLE
Exception in PrismApplication constructor on UWP 

### ISSUE THREAD

**Issue by JGrzybowski** [PrismLibrary/Prism#466]
Hello, when I try to run application on UWP in release mode I get such exception in constructor of App() which I have in PCL.
```
  System.NotImplementedException was unhandled
  HResult=-2147467263
  Message=The method or operation is not implemented.
  Source=Windows
  StackTrace:
       at Windows.UI.Xaml.Setter.get_Value()
       at Xamarin.Forms.Platform.UWP.WindowsResourcesProvider.GetStyle(Object nativeKey)
       at Xamarin.Forms.Platform.UWP.WindowsResourcesProvider.GetSystemResources()
       at Xamarin.Forms.Application..ctor()
       at Prism.PrismApplicationBase..ctor()
       at Prism.Unity.PrismApplication..ctor()
       at PrayingNetworkMobile.App..ctor()
       at PrayingNetworkMobile.WinUniversal.MainPage..ctor()
       at PrayingNetworkMobile.WinUniversal.PrayingNetworkMobile_WinUniversal_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage()
  InnerException: 
```
Is it a bug from my configuration, Prism, Xamarin one or it's Microsoft fault?

Nuget Versions I used in PCL 
```
<package id="Prism.Core" version="6.1.0" targetFramework="portable45-net45+win8+wpa81" />
<package id="Prism.Forms" version="6.1.0-pre3" targetFramework="portable45-net45+win8+wpa81" />
<package id="Prism.Unity" version="6.2.0-pre3" targetFramework="portable45-net45+win8+wpa81" />
<package id="Unity" version="4.0.1" targetFramework="portable45-net45+win8+wpa81" />
<package id="Xamarin.Forms" version="2.0.1.6505" targetFramework="portable45-net45+win8+wpa81" />
```

Nuget Versions I used in UWP application

    "Prism.Core": "6.1.0",
    "Prism.Forms": "6.1.0-pre3",
    "Prism.Unity": "6.2.0-pre3",
    "Prism.Windows": "6.0.2-pre1",
    "Unity": "4.0.1",
    "Xamarin.Forms": "2.0.1.6505"

**Comment by Shinoa-best-girl** [comment]
Did you try to reproduce your problem using blank app(or hello world)?

**Comment by brianlagunas** [comment]
For UWP, you have to use Prism.Unity.Forms NuGet.  This has not bee made public as it is still preview.
